# Generated by Django 3.2.9 on 2021-12-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=1990)),
                ('color', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('engine', models.FloatField()),
            ],
        ),
    ]
