# Generated by Django 3.2.9 on 2021-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_vehicle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('date_crate', models.CharField(max_length=200)),
            ],
        ),
    ]
