# Generated by Django 3.2.9 on 2021-12-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_brandfr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandFr',
        ),
    ]
